# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcopy < Formula
  desc ""
  homepage "https://github.com/TheDen/gcopy"
  version "1.10.0"
  depends_on :macos

  url "https://github.com/TheDen/gcopy/releases/download/v1.10.0/gcopy_1.10.0_darwin_all.tar.gz"
  sha256 "f7af7f16a8f1d1e9818a1d5da7f8de6c0f9c6ffdd79c7460fcd610e319690390"

  def install
    bin.install "gcopy"
  end
end
