# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcopy < Formula
  desc ""
  homepage "https://github.com/TheDen/gcopy"
  version "1.7.9"
  depends_on :macos

  on_macos do
    url "https://github.com/TheDen/gcopy/releases/download/v1.7.9/gcopy_1.7.9_darwin_all.tar.gz"
    sha256 "271e99a3fb2901afe627911f2af29bf564a2d76c607e7401fb7035517440f7db"

    def install
      bin.install "gcopy"
    end
  end
end
