# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcopy < Formula
  desc ""
  homepage "https://github.com/TheDen/gcopy"
  version "1.9.3"
  depends_on :macos

  url "https://github.com/TheDen/gcopy/releases/download/v1.9.3/gcopy_1.9.3_darwin_all.tar.gz"
  sha256 "d93a74f49362b07a84d2b956edd449f744b91ede2e4eaff77ce17df1968373d1"

  def install
    bin.install "gcopy"
  end
end
